import { z } from "zod";

const tiposConteudo = ["POSICAO", "PASSAGEM", "GOLPE", "TECNICA", "MOVIMENTO", "TRANSICAO", "QUEDA", "RASPAGEM", "FINALIZACAO", "DEFESA", "ESCAPE", "CONTROLE", "ENTRADA", "COMBINACAO", "EXERCICIO", "DRILL", "PRINCIPIO", "CONCEITO_TATICO", "PREPARACAO_FISICA", "MOBILIDADE", "AQUECIMENTO", "RECUPERACAO", "SEGURANCA", "AVALIACAO", "OUTRO"] as const;
const niveis = ["INICIANTE", "BASICO", "INTERMEDIARIO", "AVANCADO", "ESPECIALIZADO"] as const;

export const conteudoTecnicoSchema = z.object({
  modalidadeId: z.coerce.number().int().positive(), tipo: z.enum(tiposConteudo), nome: z.string().trim().min(2).max(160),
  nomeAlternativo: z.string().trim().max(160).nullish(), categoria: z.string().trim().max(100).nullish(), descricao: z.string().trim().max(4000).nullish(), objetivo: z.string().trim().max(1000).nullish(), finalidade: z.string().trim().max(1000).nullish(), posicaoInicial: z.string().trim().max(1000).nullish(), posicaoFinal: z.string().trim().max(1000).nullish(), passoAPasso: z.string().trim().max(6000).nullish(), principios: z.string().trim().max(2000).nullish(), pontosAtencao: z.string().trim().max(3000).nullish(), errosComuns: z.string().trim().max(3000).nullish(), correcoes: z.string().trim().max(3000).nullish(), aplicacoes: z.string().trim().max(3000).nullish(), defesas: z.string().trim().max(3000).nullish(), variacoes: z.string().trim().max(3000).nullish(), progressao: z.string().trim().max(3000).nullish(), regressao: z.string().trim().max(3000).nullish(), nivelDificuldade: z.enum(niveis).default("INICIANTE"), faixaEtariaMinima: z.coerce.number().int().min(0).max(100).nullish(), faixaEtariaMaxima: z.coerce.number().int().min(0).max(100).nullish(), graduacaoRecomendada: z.string().trim().max(100).nullish(), preRequisitos: z.string().trim().max(3000).nullish(), riscos: z.string().trim().max(3000).nullish(), cuidados: z.string().trim().max(3000).nullish(), contraIndicacoes: z.string().trim().max(3000).nullish(), impactoFisico: z.string().trim().max(1000).nullish(), impactoTecnico: z.string().trim().max(1000).nullish(), impactoTatico: z.string().trim().max(1000).nullish(), impactoCognitivo: z.string().trim().max(1000).nullish(), equipamentos: z.string().trim().max(1000).nullish(), duracaoSugeridaSegundos: z.coerce.number().int().min(30).max(14400).default(300), repeticoesSugeridas: z.coerce.number().int().min(1).max(1000).nullish(), observacoesProfessor: z.string().trim().max(3000).nullish(), conteudoPaiId: z.coerce.number().int().positive().nullish(), tags: z.array(z.string().trim().min(1).max(50)).max(12).default([]),
});

export const templatePlanejamentoSchema = z.object({
  modalidadeId: z.coerce.number().int().positive().nullish(), nome: z.string().trim().min(2).max(120), descricao: z.string().trim().max(1000).nullish(), publico: z.string().trim().max(100).nullish(),
  etapas: z.array(z.object({ tipo: z.enum(["AQUECIMENTO", "JOGO", "TECNICA", "SPARRING", "PAUSA", "ALONGAMENTO"]), titulo: z.string().trim().min(2).max(120), duracaoSegundos: z.coerce.number().int().min(30).max(14400), obrigatoria: z.boolean().default(false), descricao: z.string().trim().max(1000).nullish() })).min(1).max(20),
});
